services:

  postgres:
    image: postgres:17
    container_name: balanceflow-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: balanceflow-redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: balanceflow-app
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: