spring.application.name=balanceflow-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/balanceflow
spring.datasource.username=postgres
spring.datasource.password=Hdk@10062005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080